-- Run this in Supabase SQL Editor for the MVP.

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  name text not null,
  date date not null,
  count integer not null default 0 check (count >= 0),
  updated_at timestamptz not null default now()
);

create unique index if not exists entries_name_date_key
  on public.entries (name, date);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists entries_set_updated_at on public.entries;
create trigger entries_set_updated_at
before update on public.entries
for each row
execute function public.set_updated_at();

alter table public.entries enable row level security;

drop policy if exists entries_select_all on public.entries;
create policy entries_select_all
on public.entries
for select
to anon
using (true);

drop policy if exists entries_insert_all on public.entries;
create policy entries_insert_all
on public.entries
for insert
to anon
with check (true);

drop policy if exists entries_update_all on public.entries;
create policy entries_update_all
on public.entries
for update
to anon
using (true)
with check (true);
